script: echo "Lol" > test_file.txt
deploy:
  provider: releases
  api_key:
    secure: MLqz0miMOy/SJKEbOdNBmvAVxykc+4YQcnu/T5hAlTMNTseVK26j0Aazbk8DjcOIhOuwITeiJs2OqxQWsqkAG5+VY7U6bCcEWOhoICub5WJqDqMRFPYCOQ+iCLVkuYpfnmiZT8khjSsYTHKVO6VY2ZDJEQ91CIx2EVfXTLk/nsRrqFF5kmsVdLXASwLhmHGbuXES/EfQorhPet05hCPxdxtAPRjDfVKRcjTQXDMogqctMfJkS2C4Qzcy72vmpB/EeR6yxXTYKz5yCDZn+aqMBADUrYXqkdktxeSN0sFa/BMmdXBQ0EOXIrZUN18TSGL59VhQvkie4FkF924gEiIaMQuZgubUjXVCRUIHzXFdnbkn7zZqTpF+PciPv7ZARBwwDXLacJRqAQdoHm+Ey51JcMtP2rFJk4GbONbZbRYyNGSTp7Acqq8mLoraKcmLNhs40+wUeHsHOQM0k2t52SgKmmAanJQH1tlTX7aVJO1mljP4KOBoOci/FfDvK3bliWLCuKPlacJGpmqUIGBZtgwnK5mPYS2hZmMXo1U52Y1V5N9FEtR2apSkaCa1Kv74GHiFlUcigDgW7/FevMbFSfvxpoYpU7trgSQYH25RO1MYK1A+/0XpDb3bKUcn7iSQUwHqcpxD3fowy57hl0SJiQqshPBlYfG+9FWa/95+desUL7o=
  file: test_file.txt
  on:
    repo: msullivan/travis-testing
