if: tag IS present

matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.7

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker pull $DOCKER_IMAGE
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
  fi


install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/build-linux-wheels.sh
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export MYPY_USE_MYPYC=1
    export PYTHONPATH="$PWD/mypyc:$PYTHONPATH"
    clean_code mypy HEAD
    build_wheel mypy x86_64
  fi


deploy:
  provider: releases
  api_key:
    secure: MLqz0miMOy/SJKEbOdNBmvAVxykc+4YQcnu/T5hAlTMNTseVK26j0Aazbk8DjcOIhOuwITeiJs2OqxQWsqkAG5+VY7U6bCcEWOhoICub5WJqDqMRFPYCOQ+iCLVkuYpfnmiZT8khjSsYTHKVO6VY2ZDJEQ91CIx2EVfXTLk/nsRrqFF5kmsVdLXASwLhmHGbuXES/EfQorhPet05hCPxdxtAPRjDfVKRcjTQXDMogqctMfJkS2C4Qzcy72vmpB/EeR6yxXTYKz5yCDZn+aqMBADUrYXqkdktxeSN0sFa/BMmdXBQ0EOXIrZUN18TSGL59VhQvkie4FkF924gEiIaMQuZgubUjXVCRUIHzXFdnbkn7zZqTpF+PciPv7ZARBwwDXLacJRqAQdoHm+Ey51JcMtP2rFJk4GbONbZbRYyNGSTp7Acqq8mLoraKcmLNhs40+wUeHsHOQM0k2t52SgKmmAanJQH1tlTX7aVJO1mljP4KOBoOci/FfDvK3bliWLCuKPlacJGpmqUIGBZtgwnK5mPYS2hZmMXo1U52Y1V5N9FEtR2apSkaCa1Kv74GHiFlUcigDgW7/FevMbFSfvxpoYpU7trgSQYH25RO1MYK1A+/0XpDb3bKUcn7iSQUwHqcpxD3fowy57hl0SJiQqshPBlYfG+9FWa/95+desUL7o=
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
  on:
    tags: true
