if: tag IS present

matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: MB_PYTHON_VERSION=3.7

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker pull $DOCKER_IMAGE
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
  fi


install: |
  # Output something every 10 minutes or Travis kills the job
  while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-linux-wheels.sh
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export MYPY_USE_MYPYC=1
    export MYPYC_OPT_LEVEL=3
    export PYTHONPATH="$PWD/mypyc:$PYTHONPATH"
    clean_code mypy HEAD
    build_bdist_wheel mypy x86_64
  fi
  kill %1


deploy:
  provider: releases
  api_key:
    secure: g9oZ6Lf4iBYAbsC+SAxomyC3lP0xJOY+bZ0jh5oAo6x2DvSf77rPpJ1DGaTIS+gwiAk4OhKix0FLLULY0/c6rN5FZGC74DAh0K0rV7RM3DD/frGEPul9ZgaJj52xhW36Ub1bYiANLGk+ZEiE82ABBrd4+ELC5OI3N4BnitfwRnlQlh87xA0S91HgkR+Wk6113F7CmUBirrQ1kuIUjqSqQyfURpEeTaOgA99ttZrSuBXC5WHoqn7UGqXYCv5npHeVnll/NGMwsqka+VOlr6Rovww6htCiws0J3Kga8WJOrGyBgemVCw+ODUAWEgtlXMpjGemuR7U3DmeiJRwF5XQAwDwNWPxdlE5+xucyoh2mL6KSuS26Be0BvRvye3ZF+ZjBw6z/S11rUEzBjEAafG1Hi4M6WFuOst9lm22WfCA4hukcsb7S/envqOa5m5ubS+I+dbcXeVltVmpwQ0mpCMgnlsgjcoJZwXNMFzlL52N4JM1pDCVyziT5+G0Cts1lrUO+iVrIarhgKUJI7/VJRTsdcTIGZ9tnXRmIKFu3WE84T/2S6aAPolvpEznJUgxWW2CMrUgWayz2ztqolCdVXCzDB8qtEp50+2IBpBkjlkiUICtPWWZ2MFunH8cIxvseEW7hxt/4Z/5H0neWG2qohAH6Z09hd2zVQvjZM52CPAxGmTg=
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
  on:
    tags: true
